SELECT
    NAME = (P.NAME_FULL_FORMATTED),
    MRN = (PA.ALIAS),
    FIN = (EA.ALIAS),
    DOB = (P.BIRTH_DT_TM) "DD/MM/YYYY",

    R.PERFORMED_DT_TM "DD/MM/YYYY HH:MM",
    R_RECON_TYPE_FLAG = 
        IF(R.RECON_TYPE_FLAG = 1) "Admission"
        ELSEIF(R.RECON_TYPE_FLAG = 2) "Transfer"
        ELSEIF(R.RECON_TYPE_FLAG = 3) "Discharge"
        ELSEIF(R.RECON_TYPE_FLAG = 4) "Short Term Leave"
        ELSEIF(R.RECON_TYPE_FLAG = 5) "Return From Short Term Leave"
        ENDIF,

    R_RECON_STATUS_CD = UAR_GET_CODE_DISPLAY(R.RECON_STATUS_CD),
    PERFORMER = pr.name_full_formatted,
    Personnel_ID = (pr.person_id),

    HOSPITAL = UAR_GET_CODE_DISPLAY(ELH.LOC_FACILITY_CD),
    BUILDING = UAR_GET_CODE_DISPLAY(ELH.LOC_BUILDING_CD),
    WARD = IF (ELH.LOC_NURSE_UNIT_CD = 21119843.00)
        "CUMH-Dr Orfhlaith Sullivan AN Clinic"
        ELSE UAR_GET_CODE_DISPLAY(ELH.LOC_NURSE_UNIT_CD)
        ENDIF,

    ELH_LOC_ROOM_DISP = UAR_GET_CODE_DISPLAY(ELH.LOC_ROOM_CD),
    ELH_LOC_BED_DISP = UAR_GET_CODE_DISPLAY(ELH.LOC_BED_CD),
    Med_Service = UAR_GET_CODE_DISPLAY(ELH.MED_SERVICE_CD),
    
    ELH_Update_DT_TM = ELH.UPDT_DT_TM "DD/MM/YYYY HH:MM",
    Activity_Date = ELH.ACTIVITY_DT_TM "DD/MM/YYYY HH:MM",
    Admit_Date = ELH.ARRIVE_DT_TM "DD/MM/YYYY HH:MM",
    Discharge_Date = E.DEPART_DT_TM "DD/MM/YYYY HH:MM",

    ELH_LOC_FACILITY_DISP = UAR_GET_CODE_DISPLAY(ELH.LOC_FACILITY_CD),
    ELH_LOC_NURSE_UNIT_DISP = UAR_GET_CODE_DISPLAY(ELH.LOC_NURSE_UNIT_CD)

FROM
    ENCNTR_LOC_HIST ELH,
    ENCOUNTER E,
    ORDER_RECON R,
    PERSON P,
    PERSON_ALIAS PA,
    ENCNTR_ALIAS EA,
    PRSNL PR

PLAN ELH WHERE 
    ELH.END_EFFECTIVE_DT_TM >= CNVTDATETIME("01-APR-2025 00:00")
    AND ELH.BEG_EFFECTIVE_DT_TM <= CNVTDATETIME("23-APR-2025 23:59")
    AND ELH.ACTIVE_IND = 1
    AND ELH.ARRIVE_DT_TM IS NOT NULL

JOIN E WHERE 
    ELH.ENCNTR_ID = E.ENCNTR_ID
    AND E.ARRIVE_DT_TM BETWEEN CNVTDATETIME("01-APR-2025 00:00") AND CNVTDATETIME("23-APR-2025 23:59")

JOIN R WHERE 
    OUTERJOIN(ELH.ENCNTR_ID) = R.ENCNTR_ID
    AND R.PERFORMED_DT_TM >= OUTERJOIN(CNVTDATETIME("01-APR-2025 00:00"))
    AND R.PERFORMED_DT_TM <= OUTERJOIN(CNVTDATETIME("23-APR-2025 23:59"))
    AND R.PERFORMED_DT_TM >= OUTERJOIN(ELH.BEG_EFFECTIVE_DT_TM)
    AND R.PERFORMED_DT_TM <= OUTERJOIN(ELH.END_EFFECTIVE_DT_TM)

JOIN P WHERE 
    E.PERSON_ID = P.PERSON_ID
    AND P.BIRTH_DT_TM < CNVTLOOKBEHIND("5,Y")
    AND P.NAME_FULL_FORMATTED NOT IN ("Zzz*", "Test,*", "Testing,*")

JOIN PA WHERE 
    P.PERSON_ID = PA.PERSON_ID
    AND PA.PERSON_ALIAS_TYPE_CD = 10.00 ;MRN
    AND PA.END_EFFECTIVE_DT_TM > SYSDATE
    AND PA.ALIAS_POOL_CD = 14504365 ; Adjust alias pool as needed

JOIN EA WHERE 
    E.ENCNTR_ID = EA.ENCNTR_ID
    AND EA.ENCNTR_ALIAS_TYPE_CD = 1077.00 ; FIN
    AND EA.ALIAS = "I*"

JOIN PR WHERE 
    OUTERJOIN(R.PERFORMED_PRSNL_ID) = PR.PERSON_ID

ORDER BY
    ELH_Update_DT_TM

WITH MAXREC = 100000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 60
