SELECT
    NAME = P.NAME_FULL_FORMATTED
  , MRN = PA.ALIAS
  , DOB = P.BIRTH_DT_TM "DD/MM/YYYY"
  , ORDER_ID = O.ORDER_ID
  , ADMIN_TIME = MAE.BEG_DT_TM "DD/MM/YYYY HH:MM"
  , ADMIN_DOSE = CNVTREAL(CE.RESULT_VAL)
  , ADMIN_UNIT = UAR_GET_CODE_DISPLAY(CE.RESULT_UNITS_CD)
  , ORDER_MNEMONIC = OI.ORDER_MNEMONIC
  , MEDICATION_NAME = O.ORDERED_AS_MNEMONIC
  , GENERIC_NAME = O.HNA_ORDER_MNEMONIC
  , EVENT_TYPE = UAR_GET_CODE_DESCRIPTION(MAE.EVENT_TYPE_CD)
  , MED_TYPE = UAR_GET_CODE_DISPLAY(O.MED_ORDER_TYPE_CD)
  , ORDER_START = O.CURRENT_START_DT_TM "DD/MM/YYYY"
  , ORDER_END = O.DISCONTINUE_EFFECTIVE_DT_TM "DD/MM/YYYY"
  , HOSPITAL = UAR_GET_CODE_DISPLAY(E.LOC_FACILITY_CD)
  , BUILDING = UAR_GET_CODE_DISPLAY(E.LOC_BUILDING_CD)
  , WARD = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
  , CE_RESULT_STATUS_DISP = UAR_GET_CODE_DISPLAY(CE.RESULT_STATUS_CD)
FROM
    MED_ADMIN_EVENT MAE
  , CLINICAL_EVENT CE
  , ORDERS O
  , ORDER_INGREDIENT OI
  , PERSON P
  , PERSON_ALIAS PA
  , ALIAS_POOL A
  , ENCOUNTER E
PLAN MAE 
  WHERE MAE.BEG_DT_TM BETWEEN CNVTDATETIME("01-SEPT-2025 00:00:00") ; Start Date
                           AND CNVTDATETIME("07-SEPT-2025 23:59:59") ; End Date
  AND MAE.EVENT_TYPE_CD IN (8912520.00, 8912522.00, 8912523.00) ; Administered, Not Done, Not Given

JOIN CE 
  WHERE CE.EVENT_ID = MAE.EVENT_ID
  AND CE.RESULT_STATUS_CD IN (25.0, 35.0) ; Auth, Modified
  AND CE.VALID_UNTIL_DT_TM > CNVTDATETIME(CURDATE, CURTIME)

JOIN O 
  WHERE O.ORDER_ID = MAE.TEMPLATE_ORDER_ID
  AND O.ACTIVE_IND = 1
  AND O.HNA_ORDER_MNEMONIC = "Nirsevimab" ; Define medication to search

JOIN OI 
  WHERE OI.ORDER_ID = O.ORDER_ID
  AND OI.ACTION_SEQUENCE = O.LAST_INGRED_ACTION_SEQUENCE

JOIN P 
  WHERE O.PERSON_ID = P.PERSON_ID
  AND P.NAME_FULL_FORMATTED NOT IN ("Zzztest, *", "Test Patient, *")

JOIN PA 
  WHERE PA.PERSON_ID = P.PERSON_ID
  AND PA.PERSON_ALIAS_TYPE_CD = 10.00 ; MRN
  AND PA.ALIAS_POOL_CD = 14504365

JOIN A 
  WHERE A.ALIAS_POOL_CD = PA.ALIAS_POOL_CD

JOIN E 
  WHERE E.ENCNTR_ID = O.ENCNTR_ID
  AND E.LOC_FACILITY_CD = 14504354 ; ROH

ORDER BY
    NAME
  , GENERIC_NAME
  , O.ORDER_ID

WITH MAXREC = 20000, TIME = 300
